workflows:
  ios-build:
    name: iOS Build for TBI Attendance
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Enable iOS platform (if missing)
        script: |
          if [ ! -d "ios" ]; then
            flutter create --platforms=ios .
          fi

      - name: Build iOS release IPA
        script: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - nikhilhonkalaskar@gmail.com
